### ISSUE TITLE
provide a way to exclude a class from the PojoCodecProvider scanning

### ISSUE THREAD

**Issue by clixtec** [axelspringer/polymorphia#6]
I've found a workaround for this issue, but I don't like it so I thought I would bring it to your attention.

I've got a class Id for which I need a custom codec. Technically it is a POJO, but I need it structured differently than normal in the BSON (it's actually a wrapper for a string that gets converted to an ObjectId for use as _id). The Id class ideally should reside in a certain package which contains my other domain objects, because it is directly referenced and incorporated into them.

So I registered the overall package with the PojoCodecProvider, then built a registry around that with `CodecRegistries.fromCodecs(new IdCodec())` and `.fromRegistries(pojoCodecProvider)`. But no matter what order I did that registration, my custom codec was not being called. Only when I moved the Id class out of the registered package, was its codec used.

Example setup:
```
CodecRegistry overallRegistry = fromRegistries(
		MongoClient.getDefaultCodecRegistry(),
		fromCodecs(
			new IdCodec()),
		fromProviders(
			new EnumCodecProvider(),
			createPojoCodecProvider()));

private PojoCodecProvider createPojoCodecProvider() {
	return PojoCodecProvider.builder()
		.register(Id.class.getPackage().getName())
		.build();
}
```

I tried switching the parameter order to `fromRegistries`, creating an IdCodecProvider and putting it in the `fromProviders` parameters, then varying the order of those parameters, etc.

One solution would be to annotate classes that should be excluded from the PojoCodecProvider's consideration. Or, the PojoCodecProvider.Builder could have an `ignore(Class<?>)` method.

Curious your thoughts on this!

**Comment by webermich** [comment]
Trying to build the CodecRegistry in "correct" order won't help to fix this issue as you already experienced.
The reason is, that all classes within a package are registered within the same PojoCodecProvider. Now, when the codec for any Pojo.class is being build, all fields within Pojo.class will need a Codec as well. The first CodecProvider being asked for these Codecs is always the PojoCodecProvider itself.
If it comes to a solution, I am a little unsure.
My first though was to use an annotation like @PojoCodecIgnore 
Drwaback though would be, that the annotated class would be always ignored by any PojoCpdecProvider you build. There could be more than just one actually within the same application.
So it might be of benefit to support both the annotation style as well as an ignore(..) style method in the PojoCodecProvider.

**Comment by clixtec** [comment]
Hm, I see the problem, I hadn't thought about multiple PojoCodecProviders.

I think I just hit a very closely related issue, involving the same Id class. Recall that I moved it to a package that is not registered with PojoCodecProvider, and that it is used by each of the domain classes that is registered. That worked to create new documents with version 1.6.2, but ...

```
Exception in thread "main" de.bild.codec.NonRegisteredModelClassException: Cannot assign 5a31caf81d17b7338c2ec35c to class co.skyhawk.ca.Id. When decoding make sure you register all classes to the PojoCodec that are used within the model!
	at de.bild.codec.MappedField.setFieldValue(MappedField.java:167)
	at de.bild.codec.BasicReflectionCodec.generateIdIfAbsentFromDocument(BasicReflectionCodec.java:180)
	at de.bild.codec.PolymorphicReflectionCodec.generateIdIfAbsentFromDocument(PolymorphicReflectionCodec.java:244)
	at de.bild.codec.PojoCodecProvider$CollectibleCodecDelegator.generateIdIfAbsentFromDocument(PojoCodecProvider.java:91)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at de.bild.codec.PojoCodecProvider$CollectibleCodecDelegator.handleInvocation(PojoCodecProvider.java:80)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87)
	at com.sun.proxy.$Proxy56.generateIdIfAbsentFromDocument(Unknown Source)
	at com.mongodb.MongoCollectionImpl.executeInsertOne(MongoCollectionImpl.java:511)
	at com.mongodb.MongoCollectionImpl.insertOne(MongoCollectionImpl.java:493)
	at com.mongodb.MongoCollectionImpl.insertOne(MongoCollectionImpl.java:487)
```

I don't entirely understand the stack trace, but the gist is that Polymorphia doesn't like the setup where some classes reachable from the registered package are not themselves in the package. That part fits with what you said up above, but leaves me with the problem that the Id class can neither be inside nor outside the registered package!

So I'm wondering whether Polymorphia's strategy of preferring its own codec is really the best. Is there any way it could delegate unrecognized classes to the rest of the registry?

**Comment by clixtec** [comment]
Oh I see. In this case I did not assign an ID prior to calling insertOne. So when it was generated for me, it could then not be assigned to my custom field of type Id.

**Comment by webermich** [comment]
Hi Sean,

if possible provide a little test snipped, since your setup implies a couple of things that I need to guess right now.
I guess you annotated your id field within your Pojo as follows
`  @Id(collectible = true, value = CustomIdGenerator.class)`
Am I correct?

If so, the PojoCodec upon encode() checks, if an the id field is not null. If null, the generator generates an id and tries to assign it.
It seems, that your generator generates an Object that is not assignable to the type declared for your id field.
Unfortunately the exception is swallowed at present, hence the message/stacktrace you see is misleading.

Anyway, I will try assembling a test for your (assumed) scenario.
Also I will create a more meaningful exception/message.

One more thing:
You wrote, that your id field is actually a pojo thing, but you need it structured differently.
Have you noticed the ability to register special ReflectionCodecs? This may be of help to.
Example: https://github.com/axelspringer/polymorphia/blob/master/src/test/java/de/bild/codec/CodecResolverTest.java

`PojoCodecProvider.builder()
                                    .register(CodecResolverTest.class)
                                    .registerCodecResolver((CodecResolver) (type, typeCodecRegistry) -> {
                                        if (TypeUtils.isAssignable(type, Base.class)) {
                                            return new DocumentCodec((Class<? extends Base>) type, typeCodecRegistry);
                                        }
                                        return null;
                                    })
                                    .build()`

**Comment by clixtec** [comment]
The Id class is a simple bean holding a string, and looks like this (slightly simplified from reality):
```
public class Id {
	private String val;
	
	public Id() {
		this.val = null;
	}
	
	public String getVal() {
		return val;
	}

	public void setVal(String val) {
		this.val = val;
	}
}
```
It is needed because the Id class has to be compilable with GWT, which ObjectId isn't. The IdCodec lets me serialize an ObjectId from "_id" directly to the "val" field, and vice versa. I mean, the default encoding would be `_id: {val: ObjectId(...)}` whereas my codec makes it `_id: ObjectId(...)`.

I'm not actually use the Id Generator capability because I wasn't aware of it. So a typical POJO would be:
```
public class DomainClass {
	@de.bild.codec.annotations.Id(collectible = true)
	private Id id;
	private String name;

	public DomainClass() {}
	...
}
```

My expectation was that if DomainClass.id is null on insert, the default Id generation would generate an ObjectId, and my registered IdCodec would take care of converting that to an Id instance since that is the field type. It seems like the latter part doesn't actually happen, maybe my expectation was wrong?

**Comment by webermich** [comment]
I fixed the misleading exception and created two test cases that should help you solve your issue.
https://github.com/axelspringer/polymorphia/blob/master/src/test/java/de/bild/codec/idexternal/ExternalIdCodecProviderTest.java
And with a customizable Codec for your Id:
https://github.com/axelspringer/polymorphia/blob/master/src/test/java/de/bild/codec/idspecialcodecresolver/ExternalIdCodecProviderTest.java

Also I added support for ignoring classes while package scanning.
https://github.com/axelspringer/polymorphia#ignoring-classes-during-package-scan

All deployed with verison 1.7.0

Have fun!

**Comment by webermich** [comment]
Let me answer your last question above.
When DomainClass.id is null on insert, the underlying Mongo Java Driver will call `generateIdIfAbsentFromDocument` on `Codec<DomainClass>`
After that id was gnerated and after that id was set within the instance of Domainclass, the entity gets persisted to the database.

So first the Id is generated and then the `Codec<CustomId>` encodes the CustomId to the database.

Having said this, I understand your expectation, that magically an ObjectId would be generated and converted to your Id.class. Unfortunately the Polymorphia mechanism does not know how to convert from ObjectId to your Id.class 
But you can provide an Id generator that generates Ids and additionally you provide a Codec that performs encoding/decoding of that Id-type.

Having said all this, please keep in mind that the "_id" field in mongo can be of arbitrary type.
It could be - and most often is - an ObjectId. It could as well be an Object that wraps an ObjectId and any other additional properties you might even think of.

One use case could be to have an ID consiting for a tuple as follows:
```java
  public class VersionId {
        ObjectId id;
        int version;
    }
```
Using this Object as an Id within your mongo db might be of benefit if you need to cluster multiple versions of the same thing. The VersionId.id field for documents of the same thing may be equal, whereby the version differs. You can then query all versions of a given VersionId.id easily.

Please refer to the test section within the codebase to find more examples on this topic.
https://github.com/axelspringer/polymorphia/tree/master/src/test/java/de/bild/codec/id

Let me know if I can close this ticket?

**Comment by clixtec** [comment]
Thanks for the explanation. Yes, please close the ticket.

By the way, thanks very much for your excellent work on this project. I had made a stab at a generic pojo codec before I became aware of your project and the Mongo one, and it was not very much fun!

**Comment by webermich** [comment]
Thanks for the flowers!
Closing the ticket now.
